function showBridge(qIdx, optIdx) {
  const bridges = [
    [
      { eye: 'LO QUE ESTO DICE DE TI', txt: 'Eso que se apaga no eres tu apagandote.<br><br>Es tu cerebro entrando en modo espera, buscando una senal de que estas a salvo.<br><br>Cuando esa senal no llega, el sistema nervioso interpreta el silencio de el como una amenaza. No como descuido. Como peligro.<br><br>Por eso no sabes como empezar. No es falta de valor. Es que el cerebro bajo amenaza no puede conectar. Solo puede protegerse.<br><br>Eso tiene solucion. Pero no es la que probablemente has intentado.' },
      { eye: 'LO QUE ESTO DICE DE TI', txt: 'Esa irritacion silenciosa es una de las senales mas inteligentes que tiene tu cuerpo.<br><br>Te esta diciendo que algo no esta siendo recibido como lo necesitas.<br><br>Cuando lo guardas, no desaparece, se acumula. Y sale despues, en el momento equivocado, con mas fuerza de la que la situacion merecia.<br><br>No es tu caracter. Es un patron aprendido. Y los patrones aprendidos se pueden cambiar.' },
      { eye: 'LO QUE ESTO DICE DE TI', txt: 'Buscar conexion no es el problema. Es lo mas humano que existe.<br><br>Cada vez que buscas mas, el da un paso hacia atras.<br><br>No porque no te ame. Sino porque el cerebro masculino interpreta la busqueda como presion. Y ante la presion, su respuesta automatica es crear distancia.<br><br>No huye de ti. Huye de la sensacion.<br><br>Esa diferencia lo cambia todo.' }
    ],
    [
      { eye: 'ESO NO ES AMOR. ESO ES PERDIDA.', txt: 'Bajar el volumen de quien eres para que el no se sienta amenazado no es un acto de amor. Es una forma de desaparecer poco a poco.<br><br>Mientras mas te achicas, menos te respeta, aunque no sea su intencion.<br><br>La mujer que el necesita al lado no es la que se hace pequena. Es la que sabe mantenerse entera sin necesidad de aplastarlo.<br><br>Eso se aprende. Y empieza por saber que esta pasando en tu cabeza cuando decides bajar ese volumen.' },
      { eye: 'EL MODO QUE TE SALVA AFUERA TE CUESTA ADENTRO', txt: 'Ese modo ejecutiva que funciona perfectamente en tu trabajo, dentro de tu relacion activa exactamente la resistencia que no quieres.<br><br>No porque estes haciendo algo malo. Sino porque el no es un colaborador. Es tu pareja. Y con las personas que amamos, el control produce lo contrario de la conexion.<br><br>La solucion no es apagar quien eres. Es aprender cuando usar que version de ti.' },
      { eye: 'ESA MUJER QUE NO RECONOCES TIENE UN NOMBRE', txt: 'Cuando dices que no te reconoces en tu relacion, no estas siendo dramatica. Estas describiendo algo real.<br><br>La version de ti que aparece bajo presion emocional no es quien eres. Es quien aprendiste a ser cuando el sistema nervioso siente que algo importante puede perderse.<br><br>Esa mujer no es tu identidad. Es una respuesta de emergencia que ya no necesitas seguir usando.' }
    ],
    [
      { eye: 'TU UMBRAL DE TOLERANCIA TE DICE ALGO IMPORTANTE', txt: 'La intolerancia a la tension no es impaciencia ni mal caracter.<br><br>Tu sistema nervioso aprendio que el silencio y la distancia son peligrosos. Entonces actua rapido para cerrar esa brecha antes de que duela mas.<br><br>El problema es que el, en ese mismo momento, necesita exactamente lo contrario: espacio para procesar.<br><br>Dos sistemas en colision. Ninguno equivocado. Pero sin forma de coordinarse, el conflicto siempre termina igual.' },
      { eye: 'EL SILENCIO QUE TE PROTEGE TAMBIEN TE ATRAPA', txt: 'Callarse en el conflicto parece la opcion madura. Y en ese momento, lo es.<br><br>Pero lo que guardas no desaparece. Se acumula hasta que sale en el momento equivocado, con mas intensidad de la que la situacion merecia.<br><br>No es que explotes sin razon. Es que no tienes todavia una forma de soltar lo que guardas antes de que llegue al limite. Esa forma existe.' },
      { eye: 'LA DIFERENCIA ENTRE QUEJA Y PETICION LO CAMBIA TODO', txt: 'Hay dos versiones de la misma necesidad: la que ataca y la que invita.<br><br>Nunca me escuchas y Necesito que me escuches ahora vienen del mismo dolor. Pero producen resultados completamente distintos.<br><br>La primera cierra. La segunda abre.<br><br>No es manipulacion. Es comunicar desde tu centro en lugar de desde tu herida.' }
    ],
    [
      { eye: 'EL CONOCIMIENTO Y EL ENTRENAMIENTO NO SON LO MISMO', txt: 'El cerebro bajo presion emocional no tiene acceso a lo que sabes intelectualmente. En ese momento, el sistema mas antiguo toma el control, el que solo conoce el miedo y la defensa.<br><br>Todo lo que aprendiste en terapia y libros vive en una parte del cerebro. La reaccion en el conflicto vive en otra.<br><br>Para conectarlas no necesitas mas informacion. Necesitas practica en el momento de la presion. No aprender mas. Entrenar diferente.' },
      { eye: 'TU CRECIMIENTO NO ES EL PROBLEMA', txt: 'Crecer no deberia alejarte de la persona que amas. Pero sin las herramientas correctas, el crecimiento de uno hace sentir al otro que se queda atras.<br><br>El, en lugar de pedirte que lo esperes, hace lo unico que sabe: se queda quieto donde esta.<br><br>La solucion no esta en frenarte. Esta en aprender a traerlo contigo de una forma que no lo haga sentir pequeno.' },
      { eye: 'ALGO IMPORTANTE SOBRE ESPERAR QUE EL CAMBIE PRIMERO', txt: 'Esta es la trampa mas comun y la mas costosa.<br><br>Esperar a que el haga su parte es darle a el el control de cuando cambia tu vida.<br><br>Mientras esperas, tu sigues pagando el costo.<br><br>La salida no esta en dar mas. Esta en cambiar el tipo de movimiento. Uno que no dependa de que el reaccione primero.<br><br>Eso es soberania. Y empieza con una decision, no con el.' }
    ],
    [
      { eye: 'AHI ESTA LA CLAVE', txt: 'La fuerza que funciona en todos los demas contextos no falla en tu relacion porque seas diferente ahi.<br><br>Falla porque en tu relacion hay algo en juego que en ningun otro lugar existe: el miedo a perder algo que importa de verdad.<br><br>Ante ese miedo, la fuerza se convierte en control, el control en distancia, y la distancia en ese no entiendo por que.<br><br>No es un misterio. Es un patron. Y los patrones se interrumpen.' },
      { eye: 'NO TIENES QUE ELEGIR', txt: 'Esa sensacion de que tu crecimiento y tu relacion estan en tension no es una verdad permanente.<br><br>Es el resultado de dos personas sin un lenguaje comun para crecer en la misma direccion.<br><br>Tu puedes seguir siendo quien eres y al mismo tiempo aprender a incluirlo sin que eso te frene ni lo aplaste a el.<br><br>Eso no requiere que el cambie primero. Solo que tu cambies el punto de partida.' },
      { eye: 'ESE AGOTAMIENTO ES REAL. Y TIENE UNA SALIDA.', txt: 'El agotamiento de dar siempre mas y recibir siempre menos es uno de los dolores mas silenciosos en una relacion.<br><br>No te lo inventaste. Diste de verdad. Y eso no fue suficiente.<br><br>Pero dar mas de lo mismo no va a producir resultados diferentes.<br><br>La salida no esta en dar mas. Esta en cambiar el tipo de movimiento. Uno que no dependa de que el reaccione primero.' }
    ]
  ];
  const b = bridges[qIdx][optIdx];
  const w = document.getElementById('q-wrap');
  w.classList.remove('qin'); w.classList.add('qout');
  setTimeout(() => {
    w.innerHTML = '<span class="q-num" style="color:var(--gold-primary);letter-spacing:2px;font-size:10px;">' + b.eye + '</span><div style="font-family:var(--font-elegant);font-size:clamp(15px,3.5vw,18px);font-style:italic;line-height:1.8;color:rgba(240,230,234,0.85);margin-top:20px;">' + b.txt + '</div><button class="btn-cta" style="margin-top:32px;width:100%;" onclick="nextQ()">Continuar \u2192</button>';
    w.className = 'q-wrap';
    requestAnimationFrame(() => w.classList.add('qin'));
  }, 260);
}
